// Code generated by "stringer -type=Swimmer_Status"; DO NOT EDIT.

package sealeye

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Swimmer_Error-0]
	_ = x[Swimmer_Error_Flag-1]
	_ = x[Swimmer_Error_Flag_Type-2]
	_ = x[Swimmer_Error_Flag_Unrecognized-3]
	_ = x[Swimmer_Error_Flag_NotFound-4]
	_ = x[Swimmer_Error_Underflow-5]
	_ = x[Swimmer_Error_Underflow_Flag-6]
	_ = x[Swimmer_Error_Underflow_End-7]
	_ = x[Swimmer_Error_Underflow_Subcommand-8]
	_ = x[Swimmer_Error_Overflow-9]
	_ = x[Swimmer_Helped-0]
}

const _Swimmer_Status_name = "Swimmer_ErrorSwimmer_Error_FlagSwimmer_Error_Flag_TypeSwimmer_Error_Flag_UnrecognizedSwimmer_Error_Flag_NotFoundSwimmer_Error_UnderflowSwimmer_Error_Underflow_FlagSwimmer_Error_Underflow_EndSwimmer_Error_Underflow_SubcommandSwimmer_Error_Overflow"

var _Swimmer_Status_index = [...]uint8{0, 13, 31, 54, 85, 112, 135, 163, 190, 224, 246}

func (i Swimmer_Status) String() string {
	if i < 0 || i >= Swimmer_Status(len(_Swimmer_Status_index)-1) {
		return "Swimmer_Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Swimmer_Status_name[_Swimmer_Status_index[i]:_Swimmer_Status_index[i+1]]
}
